name: Deploy DEV
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install databricks-bundle databricks-cli databricks-sdk==0.*
      - name: Configure Databricks auth (PAT)
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          UC_CATALOG: ${{ secrets.UC_CATALOG }}
          UC_SCHEMA_DEV: ${{ secrets.UC_SCHEMA_DEV }}
        run: |
          echo "DATABRICKS_HOST is set"
      - name: Deploy bundle to DEV
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          UC_CATALOG: ${{ secrets.UC_CATALOG }}
          UC_SCHEMA_DEV: ${{ secrets.UC_SCHEMA_DEV }}
        run: |
          databricks bundle deploy --target dev
      - name: Run training job
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks bundle run train_lapse_model --target dev
